// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDef62aWjqDS2sOqpfRBLyUv6PGxlJoPCU',
    appId: '1:56341758245:web:1db0e739042dfa2ae79acc',
    messagingSenderId: '56341758245',
    projectId: 'lesson46-992e4',
    authDomain: 'lesson46-992e4.firebaseapp.com',
    databaseURL: 'https://lesson46-992e4-default-rtdb.firebaseio.com',
    storageBucket: 'lesson46-992e4.appspot.com',
    measurementId: 'G-RSL9SM48G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2FAvyCBI9BZpGrncrDO8pP8DOdrBeX2M',
    appId: '1:56341758245:android:89bea0451e38bdb8e79acc',
    messagingSenderId: '56341758245',
    projectId: 'lesson46-992e4',
    databaseURL: 'https://lesson46-992e4-default-rtdb.firebaseio.com',
    storageBucket: 'lesson46-992e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD00BjNu12H9J7RnSBgZTOCeGme8r1u3z4',
    appId: '1:56341758245:ios:78be079b9425aa04e79acc',
    messagingSenderId: '56341758245',
    projectId: 'lesson46-992e4',
    databaseURL: 'https://lesson46-992e4-default-rtdb.firebaseio.com',
    storageBucket: 'lesson46-992e4.appspot.com',
    iosBundleId: 'com.example.restaurantProject',
  );
}
